language: go

env:
  global:
    - CC_TEST_REPORTER_ID=d21cbd9c06e8e89a1be2dbd52b76d9b037c2895189cb592b0f88a6fc19b85285

go:
  - master

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -gcflags=-l -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
